# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'XXDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for XXDemo
  pod 'XiangxCore', :path => './XiangxCore'
  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'
  pod 'Alamofire', '~> 4.5.1'
  pod 'Swinject', '~> 2.1.1'
  pod 'SteviaLayout', '~> 4.0.0'
  pod 'ObjectMapper', '~> 3.0.0'
  pod 'AlamofireObjectMapper', '~> 5.0.0'
  pod 'RxDataSources', '~> 3.0.1'
  pod 'KeychainAccess', '~> 3.1.0'

  target 'XXDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XXDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
